services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3004:3004"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      nginx:
    

  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: dbAdmin
      POSTGRES_PASSWORD: dbPass_27
      POSTGRES_DB: crm
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /home/project/backend/uploads:/backend/uploads
    networks:
        nginx:

volumes:
  pgdata:


networks:
  nginx:
    name: nginx_default
    external: true
